# Title: Load the delta AF files generated by Xing
# Author: Meixi Lin
# Date: Thu Aug 18 11:41:22 2022

# preparation --------
rm(list = ls())
cat("\014")
options(echo = TRUE, stringsAsFactors = FALSE)

setwd("/Carnegie/DPB/Data/Shared/Labs/Moi/Everyone/meixilin/grenenet")
sink(file = 'logs/ver202209/step1.0_loadDeltaAF.log')

library(data.table)
library(ggplot2)
library(dplyr)

date()
sessionInfo()

# def functions --------
get_coords <- function(affile) {
    af = readRDS(file = 'data/AF/ver202209/haplotype/AF284_0922.rds')
    afcoords = rownames(af)
    return(afcoords)
}

# def variables --------

# load data --------
# get the coordinates of the allele frequency (should be only the chr1)
afcoords = get_coords(affile = 'data/AF/ver202209/haplotype/AF284_0922.rds')
deltadt = data.table::fread('/carnegie/nobackup/scratch/xwu/grenet/haplotype-AF/delta_freq_table.txt')

# get the starting AF
startAF = readRDS(file = 'data/AF/ver202209/haplotype/AFSeed_0922.rds')$seed_mix

# calculate the s by scaling with p(1-p)
scalep = apply(deltadt[,-1],1,function(xx){xx/(startAF*(1-startAF))})
scalep

# main --------

# output files --------
dir.create('data/AF/ver202209/haplotype/DeltaP')
saveRDS(afcoords, file = 'data/AF/ver202209/haplotype/SNPcoords_922975.rds')
saveRDS(deltadt, file = 'data/AF/ver202209/haplotype/DeltaP/delta_freq.rds')
saveRDS(scalep, file = 'data/AF/ver202209/haplotype/DeltaP/scaled_delta_freq.rds')

# cleanup --------
date()
sink()
closeAllConnections()
